import QRCode from 'qrcode';

describe('Standards-Compliant QR Code Library Integration & Payload Encoding', () => {
  it('encodes exact backend payload PONDFISH_BOOKING:BK-987654 into a valid ISO/IEC 18004 QR symbol', () => {
    const payload = 'PONDFISH_BOOKING:BK-987654';
    const qrSymbol = QRCode.create(payload, { errorCorrectionLevel: 'M' });

    expect(qrSymbol).toBeDefined();
    expect(qrSymbol.modules).toBeDefined();
    expect(qrSymbol.modules.size).toBeGreaterThanOrEqual(21); // Version 1 matrix minimum dimension 21x21

    const matrixData = qrSymbol.modules.data;
    expect(matrixData.length).toBe(qrSymbol.modules.size * qrSymbol.modules.size);

    // Verify top-left finder pattern structure generated by Reed-Solomon QR encoder engine
    // Outer border dark (1) at (0,0) and (0,6)
    expect(matrixData[0]).toBe(1);
    expect(matrixData[6]).toBe(1);
  });

  it('generates distinct QR module matrices for different booking codes', () => {
    const payloadA = 'PONDFISH_BOOKING:BK-111111';
    const payloadB = 'PONDFISH_BOOKING:BK-222222';

    const qrA = QRCode.create(payloadA, { errorCorrectionLevel: 'M' });
    const qrB = QRCode.create(payloadB, { errorCorrectionLevel: 'M' });

    const dataA = Array.from(qrA.modules.data);
    const dataB = Array.from(qrB.modules.data);

    expect(dataA).not.toEqual(dataB);
  });
});
